// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Environment-aware Firebase configuration
/// Set environment variable FIREBASE_ENV=dev to use dev project
/// or FIREBASE_ENV=prod (or leave unset) to use production
enum FirebaseEnv { dev, prod }

/// Default [FirebaseOptions] for use with your Firebase apps that dynamically switches between dev and prod.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseEnv _environment = FirebaseEnv.prod;

  /// Set the environment to dev or prod
  static void setEnvironment(FirebaseEnv env) {
    _environment = env;
  }

  /// Get current environment
  static FirebaseEnv get environment => _environment;

  static FirebaseOptions get currentPlatform {
    final isDev = _environment == FirebaseEnv.dev;
    if (kIsWeb) {
      return isDev ? webDev : web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isDev ? androidDev : android;
      case TargetPlatform.iOS:
        return isDev ? iosDev : ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ===== PRODUCTION CONFIGURATIONS =====

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1RZWB8nq_siP3WNhvJob-go5of1d8pjQ',
    appId: '1:287130048801:web:4d5fb4f725e86f0ed2c660',
    messagingSenderId: '287130048801',
    projectId: 'budget-21dbe',
    authDomain: 'budget-21dbe.firebaseapp.com',
    storageBucket: 'budget-21dbe.firebasestorage.app',
    measurementId: 'G-7DVFRV8X84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqI3QbS4mqKi8VlDp16osTsM752ObjIYM',
    appId: '1:287130048801:android:ef09e101a1391448d2c660',
    messagingSenderId: '287130048801',
    projectId: 'budget-21dbe',
    storageBucket: 'budget-21dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDSqVQzHYqU24Sh3W0ansMJ0ef-ydVQ8',
    appId: '1:287130048801:ios:dced6df78cd0acc0d2c660',
    messagingSenderId: '287130048801',
    projectId: 'budget-21dbe',
    storageBucket: 'budget-21dbe.firebasestorage.app',
    iosBundleId: 'com.example.budget',
  );

  // ===== DEV CONFIGURATIONS =====

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyBYyBtpX80FB2PM58mVEjT9V3ITgqgIWAY',
    appId: '1:84010342754:web:7211d6d4fdcdc09964f43b',
    messagingSenderId: '84010342754',
    projectId: 'budget-dev-6465b',
    authDomain: 'budget-dev-6465b.firebaseapp.com',
    storageBucket: 'budget-dev-6465b.firebasestorage.app',
    measurementId: 'G-BP4VR7ZH0C',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCoNXqDAxU2QqLZry3C0PAMEvD08qP9uFE',
    appId: '1:84010342754:android:bee572d979f9dcc764f43b',
    messagingSenderId: '84010342754',
    projectId: 'budget-dev-6465b',
    storageBucket: 'budget-dev-6465b.firebasestorage.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_IOS_API_KEY',
    appId: 'YOUR_DEV_IOS_APP_ID',
    messagingSenderId: 'YOUR_DEV_MESSAGING_SENDER_ID',
    projectId: 'budget-dev-6465b',
    storageBucket: 'budget-dev-6465b.firebasestorage.app',
    iosBundleId: 'com.example.budget.dev',
  );
}
