// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1RZWB8nq_siP3WNhvJob-go5of1d8pjQ',
    appId: '1:287130048801:web:4d5fb4f725e86f0ed2c660',
    messagingSenderId: '287130048801',
    projectId: 'budget-21dbe',
    authDomain: 'budget-21dbe.firebaseapp.com',
    storageBucket: 'budget-21dbe.firebasestorage.app',
    measurementId: 'G-7DVFRV8X84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqI3QbS4mqKi8VlDp16osTsM752ObjIYM',
    appId: '1:287130048801:android:ef09e101a1391448d2c660',
    messagingSenderId: '287130048801',
    projectId: 'budget-21dbe',
    storageBucket: 'budget-21dbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDSqVQzHYqU24Sh3W0ansMJ0ef-ydVQ8',
    appId: '1:287130048801:ios:dced6df78cd0acc0d2c660',
    messagingSenderId: '287130048801',
    projectId: 'budget-21dbe',
    storageBucket: 'budget-21dbe.firebasestorage.app',
    iosBundleId: 'com.example.budget',
  );
}
